<nav class="navbar navbar-default">
<div class="container-fluid">

<div class="navbar-header">
<a class="navbar-brand" href="#">E-Voucher</a>
</div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/vouchers">Vouchers</a></li>
      <li><a href="/recipients">Recipients</a></li>
      <li><a href="/offers">Offers</a></li>
    </ul>
  </div>
</div>
</nav>
