<div class="row">
  <div class="col-sm-12" style="text-align: center; border-bottom-style: solid; border-color: #ddd">
    <strong>Deleting Offer:</strong>
  </div>
</div>

<div class="row">
  <div class="col-sm-4" style="background-color: #f9f9f9">
    <strong>Name:</strong>
  </div>
  <div class="col-sm-8">
    <?= $delete_offer['name'] ?>
  </div>
</div>

<div class="row">
  <div class="col-sm-4" style="background-color: #f9f9f9">
    <strong>Discount:</strong>
  </div>
  <div class="col-sm-8">
    <?= $delete_offer['discount'] ?>%
  </div>
</div>

<div class="row">
  <div class="col-sm-12" style="text-align: center; border-top-style: solid; border-color: #ddd">
    Are you <strong>sure</strong> you want to delete this offer?
    <a class="btn btn-danger btn-sm" href="/offer/delete/<?= $delete_offer['id'] ?>">Yes</a>
    <a class="btn btn-success btn-sm" href="/offers">No</a>
  </div>
</div>
