<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>E-Vouchers</title>
    <?php require __DIR__ . '/bootstrap.phtml'; ?>
  </head>

  <body class="container-fluid">
    <div class="row">
      <?php require __DIR__ . '/header.phtml'; ?>
    </div>

    <div class="row">
      <div class="col-sm-5">
        <h2 style='margin-top: 0px'>Listing Recipients</h2>
      </div>
      <div class="col-sm-1">

        <a class="btn btn-warning btn-sm pull-right" href="/recipient/new">+</a>
      </div>
    </div>
      <div class="row">
        <div class="col-sm-6">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">E-mail</th>
              <th scope="col">Options</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($recipients as $line): ?>
            <tr>
              <td><?= $line['name'] ?></td>
              <td><?= $line['email'] ?></td>
              <td>
                <a class="btn btn-primary btn-xs" href="/recipient/edit/<?= $line['id'] ?>">Edit</a>
                <a class="btn btn-danger btn-xs" href="/recipient/confirm/<?= $line['id'] ?>">Delete</a>
              </td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
        </div>

        <div class="col-sm-6" style="margin-top: 1%">

          <?php if (isset($message)) { ?>

            <div style="background-color: #bafbff; border-style: solid; border-color: #bad5ff; text-align: center;">
              <?= $message ?>
            </div> <br/>

         <?php  } ?>

          <?php

            if(isset($delete_recipient))
              require __DIR__ . '/recipient_delete.phtml';

            if(isset($recipient))
              require __DIR__ . '/recipient_edit.phtml';

          ?>

        </div>
      </div>
    </div>
  </body>
</html>
