<div class="row">
  <div class="col-sm-12" style="text-align: center; border-bottom-style: solid; border-color: #ddd">
    <strong>Deleting Voucher:</strong>
  </div>
</div>

<div class="row">
  <div class="col-sm-4" style="background-color: #f9f9f9">
    <strong>Code:</strong>
  </div>
  <div class="col-sm-8">
    <?= $delete_voucher['code'] ?>
  </div>
</div>

<div class="row">
  <div class="col-sm-12" style="text-align: center; border-top-style: solid; border-color: #ddd">
    Are you <strong>sure</strong> you want to delete this voucher?
    <a class="btn btn-danger btn-sm" href="/voucher/delete/<?= $delete_voucher['id'] ?>">Yes</a>
    <a class="btn btn-success btn-sm" href="/vouchers">No</a>
  </div>
</div>
